<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>

        <script type='text/javascript' src='/js/jquery.min.js' charset='utf-8'></script>
        <script type="text/javascript" src="/js/d3.v4.min.js"></script>
        <style>
            html,body{margin:0;padding:0}
        </style>

        <script type="text/javascript">

            $(document).ready(function () {
                var path = d3.path();
                path.moveTo(100, 100);//start xy

                var x1 = 100;
                var y1 = 100;
                var x2 = 500;
                var y2 = 500;
//                var x3 = (100+500)/2;
//                var y3 = (100 +500)/2;
                var x3 = (3 * x1 + x2) / 4 - 50;
                var y3 = (x1 * x1 + y1 * y1 - x2 * x2 - y2 * y2 - 2 * x1 * x3 + 2 * x3 * x2) / (2 * y1 - 2 * y2);

//                var l = Math.sqrt((x2 - x1)*(x2 - x1) + (y2 - y1)*(y2 - y1));
//                l = l/2;
//               
//                var t = (l/(Math.tan(30))) * (l/(Math.tan(30)));
//                var c = (l/(Math.cos(30))) * (l/(Math.cos(30)));
//                
//                var xx = x1*x1*x2+y1*y1*x2+t*x2-c*x2-x3*x3*x2-y3*y3*x2 - x1*x1*x3-y1*y1*x3+x3*x3*x1+y3*y3*x1-x2*x2*x1-y2*y2*x1-t*x1+c*x1+x2*x2*x3+y2*y2*x3;
//                
//                xx = xx/(2*y1*x2 - 2*y3*x2 - 2*y2*x1 + 2*y3*x1);


//                window.setInterval(function () {
//                    path.quadraticCurveTo(x3, y3, x2, y2);
//                    d3.select("svg").append("path")
//                            .attr("stroke-width", 2)
//                            .style("fill", "none")
//                            .style("stroke", "#f00")
//                            .attr("d", path)
//                            .attr("class", "edge");
//                    //path.closePath();
//                    console.debug(1);
//                }, 10000);

                path.quadraticCurveTo(x3, y3, x2, y2);
                d3.select("svg").append("path")
                        .attr("stroke-width", 2)
                        .style("fill", "none")
                        .style("stroke", "#f00")
                        .attr("d", path)
                        .attr("class", "edge")
                        .style("stroke-dasharray", "1000, 1000")
                        .transition()
                        .duration(5000)
                        .styleTween("stroke-dashoffset", function () {
                            return d3.interpolateNumber(1000, 500);
                        })
                        .delay(1000)
                        .remove();
                path.closePath();


                var chart = d3.select("canvas");
                var context = chart.node().getContext("2d");

                context.beginPath();
                context.moveTo(x1, y1);
                context.quadraticCurveTo(x3, y3, x2, y2);
                context.lineWidth = 1;
                context.strokeStyle = '#ccc';
                context.stroke();

            });
        </script>
    </head>
    <body>
        <svg width="1000px" height="700px" style="margin:0;padding:0">

        </svg>
        <canvas width="1000px" height="700px" style="position:absolute;top:0;left:0">

        </canvas>
        
    </body>
    <script>
        function aclick() {
            window.setTimeout(function () {
                //alert(1);
            }, 0);
            //alert(1);
        }
    </script> 
</html>