<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Access-Control-Allow-Origin" content="*" />
    <title>Title</title>
</head>
<body>
<h1>我是pages下的a页面</h1>
<form action="/pages/insert" method="get">
    <div>
        <label>用户名：</label>
        <input type="text" name="name" />
    </div>
    <div>
        <label>年龄：</label>
        <input type="text" name="age" />
    </div>
    <div>
        <input type="submit" value="提交"/>
    </div>
</form>
</body>
</html>