<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=9">
        <title></title>

        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/jquery.cookie.js"></script>

        <style>
            
        </style>
        <script>

            $(document).ready(function () {
                alert($.cookie("pp"));
            });

        </script>

    </head>
    <body>

    </body>
</html>