<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>

        <link rel="stylesheet" type="text/css" href="/js/semantic/semantic.min.css">
        <link rel="stylesheet" type="text/css" href="/js/slide/qap-tcha.css">
        <script>
            var termType = String(navigator.platform).toLocaleLowerCase();
        </script>
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui.touch.js"></script>
        <script type="text/javascript" src="/js/slide/qap-tcha.js"></script>
        <script src="/js/semantic/semantic.min.js"></script>
        <script src="/js/jquery.cookie.js"></script>

        <style>
            body {
                font-family: Verdana,Arial,Helvetica,sans-serif;
                margin: 0;
                background-color:#35b5d3;
                text-align: center;
                overflow: hidden;
            }
            .title{
                text-align: center;
                width: 100%;
                height: 100px;
                font-size: 60px;
                margin-top: 30px;
                line-height: 100px;
                color: #fff;
            }
            .ui.grid{
                margin:0;
            }
            .login-header {
                background-color: #0066b1;
            }

            .ui.white {
                color: #fff;
            }
            .text-center{
                text-align:center;
            }
            .ui.login-div{
                width:900px;
                margin:0 auto;
                padding:15px 30px;
                border-radius:15px;
                background-color: #fff
            }

            #message{
                font-weight:bolder
            }

            #QapTcha{
               
            }

        </style>
        <script type="text/javascript">


        </script>

    </head>
    <body>
        hello
    </body>
</html>