<div class="but-wap" style="display: inline-block" onclick="loadPage('aaa')"><span class="test-link">aaa-click</span></div>
<div class="but-wap"  style="display: inline-block" onclick="loadPage('bbb')"><span class="test-link">bbb-click</span></div>
<div class="content" style="margin:0;padding:0;margin-top: 20px">
    aaaaa
</div>

<script>
var aaa = {}; 
$(document).on("pageInit", "#aaa", function(){
    console.debug("pageInit aaa");
});    
//console.debug("a----44444444444"); 

aaa.zq = "11";

aaa.chifan = function(){
    
};
//$(document).ready
</script>

<input id="aaa-but" type="button"   />