<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body></body>
	<script src="/js/jquery-1.8.3.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript">$(function() {
	var str = {
        associatedData: [{
			enabled: 0,
			id: 19
		}],
        create_author:"小张",
        desc:"ewtwtwetew",
        group_name:"sfafdsfa",
        rule_count:1,
        isCloud:0
	}
	$.ajax({
		type: "get",
		url: "/ruleset/rulesetGoodsCatagory",
		data: {
			'insert_rows': JSON.stringify(str)
		},
		async: true,
		success: function(res) {
			console.log(JSON.parse(res));
			console.log(res);
		}
	});
})</script>
</html>